### ISSUE TITLE
Unable to generate gists

### ISSUE THREAD

**Issue by drorata** [JacobBennett/MarkdownToMedium#10]
First thanks for the amazing tool! 

Secondly, I tried to port an MD post to Medium using your tool and failed. At the 3rd step, where I should be able to get the link to the gist, I see nothing and no gist(s) are generated. I tried to revoke the token and start from scratch, but still for no vain.

Would you have an idea?

**Comment by ponnamkarthik** [comment]
I think it has some error creating gists

![](https://i.imgur.com/yxCbPxu.png)

**Comment by JacobBennett** [comment]
Hey all, this is now fixed. Was due to old expiring tokens from GitHub. Should be able to re-login and get the tool to work successfully. Thanks so much for your patience!
