### ISSUE TITLE
Does this tool work at all anymore?

### ISSUE THREAD

**Issue by treyharris** [JacobBennett/MarkdownToMedium#11]
I have tried Markdown from the extremely simple to the complex (see [here](https://gist.github.com/441e802cb19e7d6bac98b49ebd63f50d) for an example), and I’ve never gotten anything from Medium’s import page at https://medium.com/p/import but:

![import failed error from Medium](https://pbs.twimg.com/media/D7QezHrXYAAr57j?format=jpg)

I’ve also tried doing the process manually (as described by @andymcfee [here](https://medium.com/@andymcfee/how-to-import-markdown-into-medium-c06dc981bd96)) with the same result.

So—does this work at all anymore? The continued existence of the tool suggests yes? If so, any idea how I might go about troubleshooting the problem?

**Comment by rerodrigues** [comment]
@treyharris Are you still having this issue? I've imported a post right now, and worked fine for me.

**Comment by JacobBennett** [comment]
Hey all, this is now fixed. Was due to old expiring tokens from GitHub. Should be able to re-login and get the tool to work successfully. Thanks so much for your patience!
