### ISSUE TITLE
Python code block gist format

### ISSUE THREAD

**Issue by nocibambi** [JacobBennett/MarkdownToMedium#12]
When parsing a python code block, it generates a gist with `.python` format. However, Medium does not recognize this, so currently, I need to rewrite the format to `.py` by hand to make syntax highlighting to work.

![image](https://user-images.githubusercontent.com/8539674/67860726-e325b280-fb1e-11e9-811c-e7ad0917eac1.png)

![image](https://user-images.githubusercontent.com/8539674/67860705-d43f0000-fb1e-11e9-854a-d7ac1c4ae97a.png)

**Comment by switowski** [comment]
I just bumped into the same problem with .python and .shell extensions. Any chance the correct extensions could be automatically detected, so it would save some manual renaming?

**Comment by FrancescoSaverioZuppichini** [comment]
PR for .python fix #30
