### ISSUE TITLE
Get started with Github account does't work anymore

### ISSUE THREAD

**Issue by gabrielsclimaco** [JacobBennett/MarkdownToMedium#29]
I already tried to use the website in five different browsers in two different computers and always end up in a refresh loop. Gif bellow to illustrate (Chrome). 

![md-to-medium-bug](https://user-images.githubusercontent.com/8144779/133167640-a51eb5a7-2bc2-4948-a0b7-724f354f6178.gif)

**Comment by FrancescoSaverioZuppichini** [comment]
same problem from my side

**Comment by VadneyK** [comment]
same problem here. very sad. seems like website certificate has expired and maybe the github key is expired too? I see the token was updated so not sure what the issue is

**Comment by nichite** [comment]
I'm also getting this issue. It's a shame--I was pretty psyched about using this tool.

**Comment by JacobBennett** [comment]
Should be all set now folks. Thanks!
