### ISSUE TITLE
Python markdown not correctly stored in Gist

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [JacobBennett/MarkdownToMedium#9]
Thank you for the amazing project. However,  If I have a code snippet in my markdown that uses python, e.g:

```python
print(‘Hello world!’)
```
It will be converted to a gist file with .python and not .py. So there is no syntax highlighting since it has not the correct format.

**Comment by JacobBennett** [comment]
https://github.com/JacobBennett/MarkdownToMedium/blob/7b859a887956464c1f25aed4a712d6aa8ec81d37/resources/assets/js/app.js#L40

This is the line that needs to be changed.

**Comment by JacobBennett** [comment]
Deploying fix now.

**Comment by FrancescoSaverioZuppichini** [comment]
Perfect, thank you a lot :) If that is okay to you I will write an article on medium to promote this tool

**Comment by FrancescoSaverioZuppichini** [comment]
![image](https://user-images.githubusercontent.com/15908060/42898303-100392b8-8ac3-11e8-9b31-cb56314145c7.png)

Still same error :(
